### ISSUE TITLE
Calling mky

### ISSUE THREAD

**Issue by Deophius** [Sudoku-dev/Sudoku#41]
@cywanysys

Please close this issue.

**Comment by cywanysys** [comment]
I will not obey it.

**Comment by Deophius** [comment]
# What the ?

> si yang guai qi

**Comment by Deophius** [comment]
What the???
You still didn't answer me?

**Comment by Deophius** [comment]
You are too slow!

**Comment by Deophius** [comment]
Although I'm not willing to do this, but I'm going to close this issue.
You have said things that were never done so many times, which had all been a few minutes of operation on the computer.
Of course I understand that your mother expects much from you, and schoolwork had already given you toomuch pressure, but I had still expected that such a development act would be a source of relaxation for you.
However, you don't seem to understand my intent. You think I am strange. Perhaps I am, but do you know that there are yet thousands of people like me?

**Comment by Deophius** [comment]
Perhaps I had not been failing enough to undersrand your difficulties. But do you know how I had compared myself with Amanda?
Once I had been defiant and not willing to give up. I had also fought for it, strivied for it and even tried some ancient beliefs to make myself outperform her. But the truth is that some things are simply too difficult to do, so I gradually gave up.
After October 2019, I dropped behind her. But she comforted me with some simple but strange words. Although they are quite empty, but I still felt good as I was respected by my competitor. Also, you're not a competitor of mine, but friends and allies. I truly respect you and look forward to your joining.

**Comment by Deophius** [comment]
You faced a lot of difficulties during the ninth grade period. If you are ever reading this, that mrans that you have passed that period and I can speak freely of that time
You seemed quite poor, but do you remember how Jj felt the last few days?
He was simply too stressed because he couldn't find time during preps to draw his idols.
This is a kind of spirital refuge, and it need not be something other than study. Programming and chemistry are mine, and the former I belive is yours, too, although you have been denying it.
Some people ask me whether I have feelings, ehich is a pretty boring question. I have to admit that I like Amanda and Evy quite much, and my paeents weren't against that. This feeling isn't so bad as you had said, and it gave me quite a good time to keep the thoughts and create them at the same time.

**Comment by Deophius** [comment]
I'm writing this to tell you:  the only true meaning and image of yourself can be only found in your own heart. Different people have different situations to encounter, and I'm not a psychologist, even worse than Jupiter.
Just think about what you need for relaxation, and keep to it.

**Comment by Deophius** [comment]
Perhaps you can try the Tony logic. He denies to believe anything that is told to him, but he believes in his own ideas and isn't afraid of expressing them out loud.
This is quite naive, but it really helps to relieve some stress from someone like me who is defiant in nature.
As I have said, only ehat you think is the best is the best for you. If you want to join me, just open a new issue and I'll be there for you. If not and you're reading this, hope that your heart will see through the words and meet mine.
If the latter, farewell, and take good care.
And of course, greetings from Master and Jupiter.
